### ISSUE TITLE
Roadmap for 1.x

### ISSUE THREAD

**Issue by txp1035** [alitajs/codegen#15]
- [ ] 支持静态数据（无服务端部署）
- [ ] 中文翻译
- [ ] 插件内置api方便数据处理
- [ ] 支持mock格式的数据
- [ ] 支持生成文件prettier自动格式化
- [x] 支持plugin文件化，类似umi-plugin
- [x] 支持传入json配置的数据源
- [ ] 支持没有配置文件时运行向导程序
- [ ] 输出文件检查是否存在同名文件并处理
- [x] 支持内部插件配置，可以开启关闭内部插件之类的
- [x] 更方便的本地调试和测试方案
- [x] 检查流程处理是否存在报错
- [x] 外部插件加载检查
- [x] 优化提示
- [x] 内部插件优化
- [x] 支持swagger v2的数据源
- [x] 支持命令行使用
- [x] 支持引用使用
- [x] 支持外部插件
## 内部插件支持
- [x] 支持umi-mock数据生成
- [x] 支持umi-service-ts生成
- [x] 支持umi-service-js生成

**Comment by ShawDanon** [comment]
v1实现思路
- 获取数据：通过 node-fetch 和配置的 url 拿到 swagger 数据。

  - 配置：

  ```js
  exports.default = {
    swaggerUrl: '', //推荐的，优先加载命令行的url，命令行没有再加载配置的url
    plugins: [
      {
        outPath: '', //输出目录路径
        handelData: params => {
          return [{ fileName: 'api.ts', fileStr: params }];
        }, //传入swagger数据，返回集合fileName是生成的文件名，fileStr是生成的文件内容
      },
    ], //可选的
  };
  ```

- 处理数据：

  - 内置处理方式：
    - mock 数据：
    1. 支持 mockjs
    2. 支持配置数据外层，不配置则为默认值，如`{code:200,msg:'成功',data:''}`
    - service 数据：
    1. 支持 js、ts 配置

- 写入数据：配置文件获得输出文件夹路径，处理数据得到数组`[{ fileName: '', fileStr: '' }]`

**Comment by ShawDanon** [comment]
贡献：
### 安装

**Comment by ShawDanon** [comment]
:smile:

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-presets-pro/tree/master/packages/max-plugin-openapi

**Comment by txp1035** [comment]
oneapi放到外网用了啊
